#!/bin/sh
#

[ -r /etc/lsb-release ] && . /etc/lsb-release

printf "\n"
echo "\e[1;34m
 ____       _     _             _ ____  
|  _ \  ___| |__ (_) __ _ _ __ / |___ \ 
| | | |/ _ \ '_ \| |/  \` | '_ \| | __) |
| |_| |  __/ |_) | | (_| | | | | |/ __/ 
|____/ \___|_.__/|_|\__,_|_| |_|_|_____|
\e[0m"

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
printf "\n"
printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
